common_libs:
    - curl
    - wget
    - build-essential
    - software-properties-common
    - python
    - python-pip
    - ntp
    - python-dev
    - bluetooth
    - libglib2.0-dev
    - libbluetooth-dev