---

- name: Disable interactive
  shell: export DEBIAN_FRONTEND=noninteractive

- include: upgrade.yml
  sudo: yes

- name: install common packages
  apt: pkg={{ item }} state=latest update_cache=yes
  with_flattened:
    - common_libs
  sudo: yes

- name: Configuring locale to server
  copy: src=locale
        dest=/etc/default/locale
        backup=yes
  sudo: yes

- name: Configuring locale for bash
  shell: export LC_ALL=en_US.UTF-8 && export LC_CTYPE=en_US.UTF-8
  sudo: yes

- name: Configure ntp
  copy: src=ntp.conf dest=/etc/ntp.conf
  sudo: yes

- name: restart ntp
  service: name=ntp state=restarted enabled=yes
  sudo: yes