- name: Install pgsql
  apt: name={{ item}} state=present
  with_items:
    - postgresql
    - postgresql-contrib
    - python-psycopg2
    - libpq-dev

- name: ensure database is created
  postgresql_db: name={{dbname}}
  sudo_user: postgres

- name: ensure user has access to database
  postgresql_user: db={{dbname}} name={{dbuser}} password={{dbpassword}} priv=ALL
  sudo_user: postgres

- name: ensure user does not have unnecessary privilege
  postgresql_user: name={{dbuser}} role_attr_flags=NOSUPERUSER,NOCREATEDB
  sudo_user: postgres

- name: ensure no other user can access the database
  postgresql_privs: db={{dbname}} role=PUBLIC type=database priv=ALL state=absent
  sudo_user: postgres