---
# defaults for all groups

base_path: /var/www/application
build_number: ""
common_libs:
    - curl
    - wget
    - build-essential
    - software-properties-common
    - python
    - python-pip
    - ntp
    - python-dev
